"use client";
import { TrashIcon } from "../../core/task-icons";
import { AppNavigation } from "../../core/app-navigation";
import { useEffect, useMemo, useRef, useState } from "react";
import { signOut } from "../../core/local-data";
import type { RecipeSnapshot, RecipeView } from "../../../../reconstruction/core/src/recipes";
import type { PantrySnapshot, IngredientView } from "../../../../reconstruction/core/src/pantry";
import { parseRecipeCommand, type RecipeInput } from "../../../../reconstruction/core/src/recipe-input";
import { quantityString, quantityThousandths, type IngredientUnit } from "../../../../reconstruction/core/src/ingredient-input";
import { useRecipeFeed } from "../../core/use-recipe-feed";
import { usePantryFeed } from "../../core/use-pantry-feed";
import { CoreDialog, CoreFeedback } from "../../core/schedule-editor";
import { IngredientEditor } from "../core-pantry-view";
import { StepIngredientSearch } from "./step-ingredient-search";

const units: Record<IngredientUnit, string> = { g: "g", ml: "ml", piece: "piezas" };
type StepDraft = { stepKey: string; text: string; optional: boolean; ingredientId: string; ingredientRevision: number | null; quantity: string; equivalent: string; previous: boolean; hoursBefore: string; priorTitle: string; priorGroup: boolean };
function emptyStep(): StepDraft { return { stepKey: crypto.randomUUID(), text: "", optional: false, ingredientId: "", ingredientRevision: null, quantity: "", equivalent: "", previous: false, hoursBefore: "12", priorTitle: "", priorGroup: true }; }
function ingredientSummary(steps: RecipeView["steps"]) {
  const totals = new Map<string, { id: string; name: string; unit: IngredientUnit; required: bigint; optional: bigint; quantified: boolean; requiredPresence: boolean; optionalPresence: boolean; equivalents: Set<string> }>();
  for (const step of steps) if (step.ingredientId && step.unit) {
    const total = totals.get(step.ingredientId) ?? { id: step.ingredientId, name: step.ingredientName!, unit: step.unit, required: BigInt(0), optional: BigInt(0), quantified: false, requiredPresence: false, optionalPresence: false, equivalents: new Set<string>() };
    if (step.quantity) { total[step.optional ? "optional" : "required"] += quantityThousandths(step.quantity); total.quantified = true; }
    else { total[step.optional ? "optionalPresence" : "requiredPresence"] = true; if (step.equivalent?.trim()) total.equivalents.add(step.equivalent.trim()); }
    totals.set(step.ingredientId, total);
  }
  return [...totals.values()].sort((a, b) => a.name.localeCompare(b.name, "es"));
}
export function CoreRecipesView({ initial, pantry }: { initial: RecipeSnapshot; pantry: PantrySnapshot }) {
  const feed = useRecipeFeed(initial), ingredients = usePantryFeed(pantry);
  const [editor, setEditor] = useState<{ item?: RecipeView; id?: string } | null>(null), [search, setSearch] = useState("");
  const [dirty, setDirty] = useState(false);
  const [topRecipeId, setTopRecipeId] = useState<string | null>(null);
  useEffect(() => { if (!topRecipeId) return; const frame = requestAnimationFrame(() => document.getElementById(`recipe-${topRecipeId}`)?.scrollIntoView({ block: "start", behavior: "smooth" })); return () => cancelAnimationFrame(frame); }, [topRecipeId]);
  function switchEditor(next: typeof editor) { if (dirty && !window.confirm("Hay cambios sin guardar. ¿Quieres descartarlos?")) return; setDirty(false); setEditor(next); }
  const [quickName, setQuickName] = useState(""), [quickError, setQuickError] = useState<string | null>(null);
  const items = useMemo(() => {
    const query = search.toLocaleLowerCase("es");
    return feed.data.items.filter(item => item.name.toLocaleLowerCase("es").includes(query)).sort((a, b) => a.id === topRecipeId ? -1 : b.id === topRecipeId ? 1 : a.name.localeCompare(b.name, "es"));
  }, [feed.data.items, search, topRecipeId]);
  return <CoreFeedback.Provider value={{ error: feed.error, retry: feed.retry, busy: feed.busy, reattempt: feed.reattempt }}><main className="app-shell"><AppNavigation footer="Tus recetas son privadas" /><section className="workspace"><header className="topbar"><div className="breadcrumb">Cocina / <strong>Recetario</strong></div><button className="core-text-button" disabled={feed.locked || ingredients.locked} onClick={() => void signOut({ callbackUrl: "/login" })}>Cerrar sesión</button></header>
    <div className="page-content"><div className="page-heading-row"><div><p className="eyebrow">COCINA</p><h1>Recetario</h1><p className="week-range">Guarda tus recetas y organiza sus pasos.</p></div></div>
    {feed.error && <p className="pantry-error" role="alert">{feed.error} {feed.retry && <button className="core-text-button" disabled={feed.busy} onClick={feed.reattempt}>Reintentar guardado</button>}</p>}
    <label className="form-field recipe-search">Buscar receta<input type="search" value={search} onChange={event => setSearch(event.target.value)} placeholder="Nombre de la receta" /></label>
    <form className="recipe-quick-create" onSubmit={event => { event.preventDefault(); if (dirty && !window.confirm("Hay cambios sin guardar. ¿Quieres descartarlos y crear otra receta?")) return; setQuickError(null); const id = crypto.randomUUID(); try { const command = parseRecipeCommand({ action: "createRecipe", commandId: crypto.randomUUID(), id, recipe: { name: quickName, description: null, draft: true, baseServings: null, cookingMinutes: null, steps: [] } }); void feed.mutate({ action: "createRecipe", id, recipe: command.recipe }, () => { setQuickName(""); setSearch(""); setDirty(false); setTopRecipeId(id); setEditor({ id }); }); } catch (cause) { setQuickError(cause instanceof Error ? cause.message : "Escribe el nombre."); } }}><label className="form-field">Nueva receta<input id="recipe-quick-name" maxLength={250} required value={quickName} disabled={feed.locked} onChange={event => setQuickName(event.target.value)} placeholder="Nombre de la receta" /></label><button className="pantry-add-button" disabled={feed.locked || !quickName.trim()}>＋ Agregar</button></form>
    {quickError && <p className="pantry-error" role="alert">{quickError}</p>}
    <div className="recipe-core-list">{items.map(item => <article id={`recipe-${item.id}`} className="pantry-panel recipe-core-card" key={item.id}><div className="recipe-card-heading"><button className="recipe-expand-button" aria-expanded={(editor?.id ?? editor?.item?.id) === item.id} disabled={feed.busy || ingredients.busy} onClick={() => { switchEditor((editor?.id ?? editor?.item?.id) === item.id ? null : { item }); }}><span aria-hidden="true">{(editor?.id ?? editor?.item?.id) === item.id ? "▾" : "▸"}</span><span><strong>{item.name}</strong><span className="core-muted">{item.draft ? "Borrador" : "Lista"}{item.baseServings ? ` · ${item.baseServings} porciones` : ""}{item.cookingMinutes ? ` · ${item.cookingMinutes} min` : ""} · {item.steps.length} pasos</span></span></button><div className="recipe-actions"><button className="core-text-button core-icon-button" aria-label={`Retirar ${item.name}`} title="Retirar receta" disabled={feed.locked} onClick={() => { if (window.confirm(`¿Retirar «${item.name}» del recetario? Sus versiones se mantienen para respetar referencias de comidas.`)) void feed.mutate({ action: "retireRecipe", id: item.id, expectedRevision: item.revision }); }}><TrashIcon /></button></div></div>
      {(editor?.id ?? editor?.item?.id) === item.id && <RecipeEditor key={item.id} inline startInServings={editor?.id === item.id} item={item} feed={feed} ingredients={ingredients} dirtyChanged={setDirty} close={() => switchEditor(null)} saved={() => { setDirty(false); setEditor(null); }} />}
    </article>)}</div>{!items.length && <p className="today-empty">{search ? "No hay coincidencias entre las recetas cargadas." : "Todavía no tienes recetas. Crea una o comienza con un borrador."}</p>}
    {feed.data.nextId && <button className="core-text-button" disabled={feed.locked || feed.reading} onClick={() => void feed.load(feed.data.nextId!)}>Cargar más recetas</button>}</div>
  </section>{editor && !editor.item && !editor.id && <RecipeEditor feed={feed} ingredients={ingredients} close={() => { if (!feed.busy && !ingredients.busy) setEditor(null); }} />}</main></CoreFeedback.Provider>;
}
function IngredientTotals({ steps }: { steps: RecipeView["steps"] }) {
  const totals = useMemo(() => ingredientSummary(steps), [steps]); if (!totals.length) return null;
  return <section className="recipe-totals"><h3>Ingredientes para las porciones base</h3><ul>{totals.map(total => <li key={total.id}><strong>{total.name}</strong>: {total.quantified && <>{quantityString(total.required + total.optional)} {units[total.unit]}{total.optional > BigInt(0) && <small> · {quantityString(total.required)} obligatorio + {quantityString(total.optional)} opcional</small>}</>}{(total.requiredPresence || total.optionalPresence) && <>{total.quantified ? " · " : ""}{[...total.equivalents].join(" / ") || "al gusto"}{!total.requiredPresence && total.optionalPresence && <small> (opcional)</small>}</>}</li>)}</ul></section>;
}
function RecipeEditor({ item: initialItem, feed, ingredients, close, inline = false, dirtyChanged, saved, startInServings = false }: { item?: RecipeView; feed: ReturnType<typeof useRecipeFeed>; ingredients: ReturnType<typeof usePantryFeed>; close: () => void; inline?: boolean; startInServings?: boolean; dirtyChanged?: (dirty: boolean) => void; saved?: () => void }) {
  // Keep the revision paired with this draft; background refreshes must not silently rebase unsaved edits.
  const [item] = useState(initialItem);
  const [id] = useState(() => item?.id ?? crypto.randomUUID()), [name, setName] = useState(item?.name ?? "");
  const [servings, setServings] = useState(item?.baseServings ?? ""), [minutes, setMinutes] = useState(item?.cookingMinutes?.toString() ?? "");
  const [slotIds, setSlotIds] = useState<string[]>(item?.slotIds ?? []);
  const [steps, setSteps] = useState<StepDraft[]>(() => (item?.steps ?? []).map(step => ({ stepKey: step.stepKey, text: step.text, optional: step.optional, ingredientId: step.ingredientId ?? "", ingredientRevision: ingredients.data.ingredients.find(ingredient => ingredient.id === step.ingredientId)?.revision ?? null, quantity: step.quantity ?? "", equivalent: step.equivalent ?? "", previous: step.minutesBefore !== null, hoursBefore: step.minutesBefore ? String(step.minutesBefore / 60) : "12", priorTitle: step.priorTitle ?? "", priorGroup: step.minutesBefore ? step.priorGroup : true })));
  const [error, setError] = useState<string | null>(null), [ingredientStep, setIngredientStep] = useState<string | null>(null), [created, setCreated] = useState<{ stepKey: string; id: string } | null>(null);
  const [ingredientInitialName, setIngredientInitialName] = useState("");
  const [pendingStep, setPendingStep] = useState<StepDraft>(() => emptyStep());
  const [pendingIngredient, setPendingIngredient] = useState(false);
  const [ingredientSearchOpen, setIngredientSearchOpen] = useState(false);
  const servingsRef = useRef<HTMLInputElement>(null), minutesRef = useRef<HTMLInputElement>(null), stepRef = useRef<HTMLInputElement>(null), quantityRef = useRef<HTMLInputElement>(null), equivalentRef = useRef<HTMLInputElement>(null);
  const initialFocusDone = useRef(false);
  function focusField(ref: { current: HTMLInputElement | null }) { requestAnimationFrame(() => ref.current?.focus()); }
  function openIngredientSearch() { setPendingIngredient(true); setIngredientSearchOpen(true); }
  function checkQuantity(value: string) { try { if (quantityThousandths(value) <= BigInt(0)) throw new Error(); setError(null); return true; } catch { setError("Escribe una cantidad mayor que cero."); return false; } }
  const [addingStep, setAddingStep] = useState(() => !item?.steps.length);
  const draft = !servings.trim() || !minutes.trim() || !steps.length || !steps.some(step => step.ingredientId);
  const draftState = JSON.stringify({ name, servings, minutes, slotIds, pendingStep, steps: steps.map(({ ingredientRevision, ...step }) => step) });
  const [originalDraft] = useState(draftState);
  useEffect(() => { dirtyChanged?.(draftState !== originalDraft); }, [draftState, originalDraft, dirtyChanged]);
  const disabled = feed.locked || ingredients.locked;
  useEffect(() => { if (!startInServings || disabled || initialFocusDone.current) return; const frame = requestAnimationFrame(() => { servingsRef.current?.focus(); initialFocusDone.current = true; }); return () => cancelAnimationFrame(frame); }, [startInServings, disabled]);
  const [openStep, setOpenStep] = useState<string | null>(null), [ingredientPanels, setIngredientPanels] = useState<string[]>([]);
  const catalog = useMemo(() => [...ingredients.data.ingredients].sort((a, b) => a.name.localeCompare(b.name, "es")), [ingredients.data.ingredients]);
  function change(key: string, fields: Partial<StepDraft>) { setSteps(current => current.map(step => step.stepKey === key ? { ...step, ...fields } : step)); }
  function choose(key: string, ingredient: IngredientView) { if (key === pendingStep.stepKey) { setPendingStep(current => ({ ...current, ingredientId: ingredient.id, ingredientRevision: ingredient.revision, quantity: "", equivalent: "" })); setPendingIngredient(true); setIngredientSearchOpen(false); focusField(ingredient.trackingMode === "availability" ? equivalentRef : quantityRef); } else change(key, { ingredientId: ingredient.id, ingredientRevision: ingredient.revision }); }
  useEffect(() => { if (!created) return; const ingredient = ingredients.data.ingredients.find(entry => entry.id === created.id); if (ingredient) { if (created.stepKey === pendingStep.stepKey) { setPendingStep(current => ({ ...current, ingredientId: ingredient.id, ingredientRevision: ingredient.revision, quantity: "", equivalent: "" })); setPendingIngredient(true); setIngredientSearchOpen(false); focusField(ingredient.trackingMode === "availability" ? equivalentRef : quantityRef); } else setSteps(current => current.map(step => step.stepKey === created.stepKey ? { ...step, ingredientId: ingredient.id, ingredientRevision: ingredient.revision } : step)); setCreated(null); } }, [created, ingredients.data.ingredients, pendingStep.stepKey]);
  // Resolve ingredient IDs arriving in later catalog pages; do not overwrite a known revision silently.
  useEffect(() => { setSteps(current => current.map(step => { const ingredient = ingredients.data.ingredients.find(entry => entry.id === step.ingredientId); return step.ingredientRevision === null && ingredient ? { ...step, ingredientRevision: ingredient.revision } : step; })); }, [ingredients.data.ingredients]);
  function move(index: number, direction: number) { setSteps(current => { const result = [...current]; [result[index], result[index + direction]] = [result[index + direction], result[index]]; return result; }); }
  function input(): RecipeInput {
    return { name, description: null, draft, slotIds, baseServings: servings.trim() || null, cookingMinutes: minutes.trim() ? Number(minutes) : null,
      steps: steps.map(step => ({ stepKey: step.stepKey, text: step.text, optional: step.optional, ingredientId: step.ingredientId || null, expectedIngredientRevision: step.ingredientId ? step.ingredientRevision : null, quantity: step.ingredientId && catalog.find(item=>item.id===step.ingredientId)?.trackingMode !== "availability" ? step.quantity.trim() || null : null, equivalent: step.ingredientId ? step.equivalent.trim() || null : null, minutesBefore: step.previous ? Number(step.hoursBefore) * 60 : null, priorTitle: step.previous ? (step.priorGroup ? step.text.trim().slice(0,150) : step.priorTitle.trim() || null) : null, priorGroup: step.previous && step.priorGroup })) };
  }
  function addPendingStep(withoutIngredient = false) {
    if (disabled || steps.length >= 60) return;
    setError(null);
    try {
      if (!withoutIngredient && pendingIngredient && !pendingStep.ingredientId) throw new Error("Selecciona un ingrediente o pulsa Quitar ingrediente.");
      if (!withoutIngredient && pendingStep.ingredientId && catalog.find(entry => entry.id === pendingStep.ingredientId)?.trackingMode !== "availability" && !pendingStep.quantity.trim()) throw new Error("Indica la cantidad real del ingrediente.");
      const next = [...steps, withoutIngredient ? { ...pendingStep, ingredientId: "", ingredientRevision: null, quantity: "", equivalent: "" } : pendingStep];
      parseRecipeCommand({ action: "createRecipe", commandId: crypto.randomUUID(), id, recipe: { ...input(), baseServings: null, cookingMinutes: null, steps: next.map(step => ({ stepKey: step.stepKey, text: step.text, optional: step.optional, ingredientId: step.ingredientId || null, expectedIngredientRevision: step.ingredientId ? step.ingredientRevision : null, quantity: step.ingredientId && catalog.find(item=>item.id===step.ingredientId)?.trackingMode !== "availability" ? step.quantity.trim() || null : null, equivalent: step.ingredientId ? step.equivalent.trim() || null : null, minutesBefore: step.previous ? Number(step.hoursBefore) * 60 : null, priorTitle: step.previous ? (step.priorGroup ? step.text.trim().slice(0,150) : step.priorTitle.trim() || null) : null, priorGroup: step.previous && step.priorGroup })) } });
      setSteps(next); setPendingStep(emptyStep()); setPendingIngredient(false); setIngredientSearchOpen(false); setAddingStep(true); focusField(stepRef);
    } catch (cause) { setError(cause instanceof Error ? cause.message : "Revisa el paso."); }
  }
  const summary: RecipeView["steps"] = steps.flatMap(step => {
    if (!step.ingredientId) return [];
    const ingredient = catalog.find(entry => entry.id === step.ingredientId), original = item?.steps.find(entry => entry.stepKey === step.stepKey && entry.ingredientId === step.ingredientId);
    const unit = ingredient?.unit ?? original?.unit, ingredientName = ingredient?.name ?? original?.ingredientName;
    if (!unit || !ingredientName) return [];
    const quantity = ingredient?.trackingMode === "availability" ? null : step.quantity.trim() || null;
    if (quantity) { try { quantityThousandths(quantity); } catch { return []; } }
    else if (ingredient?.trackingMode !== "availability" && original?.quantity !== null) return [];
    return [{ stepKey: step.stepKey, text: step.text, optional: step.optional, ingredientId: step.ingredientId, ingredientName, unit, quantity, equivalent: step.equivalent, minutesBefore: null, priorTitle: null, priorGroup: false }];
  });
  const form = <form className="core-edit-form recipe-editor" onSubmit={event => {
    event.preventDefault(); setError(null); if (pendingStep.text.trim() || pendingStep.ingredientId) { setError("Pulsa Agregar paso antes de guardar la receta."); return; }
    try { const command = parseRecipeCommand({ action: item ? "editRecipe" : "createRecipe", commandId: crypto.randomUUID(), id, ...(item ? { expectedRevision: item.revision } : {}), recipe: input() }); void feed.mutate({ action: command.action, id, ...(item ? { expectedRevision: item.revision } : {}), recipe: command.recipe }, saved ?? close); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "Revisa la receta."); }
  }}><label className="form-field">Nombre<input required maxLength={250} disabled={disabled} value={name} onChange={event => setName(event.target.value)} /></label>
    <div className="recipe-inline-metadata"><label className="form-field">Porciones base<input ref={servingsRef} onKeyDown={event => { if (event.key === "Enter" && !event.nativeEvent.isComposing) { event.preventDefault(); if (checkQuantity(servings)) focusField(minutesRef); } }} inputMode="decimal" disabled={disabled} value={servings} onChange={event => setServings(event.target.value)} placeholder="2" /></label><label className="form-field">Tiempo de cocina · min<input ref={minutesRef} onKeyDown={event => { if (event.key === "Enter" && !event.nativeEvent.isComposing) { event.preventDefault(); const duration = Number(minutes); if (!Number.isInteger(duration) || duration < 1 || duration > 10080) { setError("El tiempo debe ser de 1 a 10080 minutos."); return; } setError(null); setAddingStep(true); focusField(stepRef); } }} type="number" min={1} max={10080} disabled={disabled} value={minutes} onChange={event => setMinutes(event.target.value)} placeholder="30" /></label><span className="recipe-badge">{draft ? "Borrador" : "Lista para planificar"}</span></div>
    {draft && <p className="core-muted">Para planificar, completa: {[!servings.trim() && "porciones", !minutes.trim() && "tiempo", !steps.length && "un paso", !steps.some(step => step.ingredientId) && "un ingrediente"].filter(Boolean).join(", ")}.</p>}
    <fieldset className="recipe-classifications" disabled={disabled}><legend>Tipos de comida</legend><div>{feed.data.slots.map(slot => <label className="core-check" key={slot.id}><input type="checkbox" checked={slotIds.includes(slot.id)} onChange={event => setSlotIds(current => event.target.checked ? [...current, slot.id] : current.filter(id => id !== slot.id))} />{slot.name}</label>)}</div><small className="core-muted">Puedes elegir varios. {feed.data.slots.length ? "Sin clasificación, aparecerá al buscar o mostrar todas." : "Agrega filas en Planificar para poder clasificarlas aquí."}</small></fieldset>
    <h3>Pasos</h3>{!steps.length && <p className="core-muted">Todavía no hay pasos. Agrega el primero; puedes incluir un ingrediente cuando lo necesites.</p>}{steps.map((step, index) => { const ingredient = catalog.find(entry => entry.id === step.ingredientId), missing = !!step.ingredientId && !ingredient, stale = ingredient && step.ingredientRevision !== null && ingredient.revision !== step.ingredientRevision; return <section className="recipe-inline-step" key={step.stepKey}><button type="button" className="recipe-expand-button" disabled={disabled} aria-expanded={openStep === step.stepKey} onClick={() => setOpenStep(openStep === step.stepKey ? null : step.stepKey)}><span aria-hidden="true">{openStep === step.stepKey ? "▾" : "▸"}</span><span>{step.ingredientId ? <><strong className="recipe-step-ingredient-title">{ingredient?.name ?? item?.steps.find(entry => entry.stepKey === step.stepKey)?.ingredientName ?? "Ingrediente"} · {ingredient?.trackingMode === "availability" || !step.quantity ? "al gusto" : `${step.quantity} ${ingredient ? units[ingredient.unit] : ""}`}{step.equivalent ? ` (${step.equivalent})` : ""}</strong><span className="core-muted">{index + 1}. {step.text || "Nuevo paso"}</span></> : <strong>{index + 1}. {step.text || "Nuevo paso"}</strong>}{step.previous && <span className="core-muted">Preparación previa · {step.hoursBefore} h antes</span>}</span>{step.optional && <span className="recipe-badge">Opcional</span>}</button>{openStep === step.stepKey && <fieldset className="recipe-step-editor" disabled={disabled}><legend>Editar paso {index + 1}</legend>
      <div className="recipe-actions"><button type="button" className="core-text-button" disabled={index === 0} onClick={() => move(index, -1)} aria-label={`Subir paso ${index + 1}`}>↑ Subir</button><button type="button" className="core-text-button" disabled={index === steps.length - 1} onClick={() => move(index, 1)} aria-label={`Bajar paso ${index + 1}`}>↓ Bajar</button><button type="button" className="core-text-button" onClick={() => setSteps(current => current.filter(entry => entry.stepKey !== step.stepKey))}>× Eliminar paso</button></div>
      <label className="form-field">Qué hacer<input required maxLength={2000} value={step.text} onChange={event => change(step.stepKey, { text: event.target.value })} /></label><label className="core-check"><input type="checkbox" checked={step.optional} onChange={event => change(step.stepKey, { optional: event.target.checked })} />Paso opcional{step.ingredientId ? " (incluye su ingrediente)" : ""}</label>
      {!step.ingredientId && !ingredientPanels.includes(step.stepKey) ? <button type="button" className="core-text-button" onClick={() => setIngredientPanels(current => [...current, step.stepKey])}>＋ Agregar ingrediente</button> : <div className="recipe-step-picker"><label className="form-field">Ingrediente del paso<select value={step.ingredientId} onChange={event => { const selected = catalog.find(entry => entry.id === event.target.value); change(step.stepKey, { ingredientId: selected?.id ?? "", ingredientRevision: selected?.revision ?? null, quantity: "", equivalent: "" }); }}><option value="">Selecciona un ingrediente</option>{missing && <option value={step.ingredientId}>Ingrediente aún no cargado</option>}{catalog.map(entry => <option key={entry.id} value={entry.id}>{entry.name} · {units[entry.unit]}{entry.hidden ? " (oculto en sugerencias)" : ""}</option>)}</select></label>
      <button type="button" className="core-text-button" onClick={() => { setIngredientInitialName(""); setIngredientStep(step.stepKey); }}>＋ Crear ingrediente personalizado</button>{missing && <p className="pantry-error">Carga más ingredientes antes de guardar o elige otro.</p>}{stale && <p className="pantry-error">Este ingrediente cambió. Revisa la unidad y cantidad; <button type="button" className="core-text-button" onClick={() => choose(step.stepKey, ingredient!)}>usar datos actuales ({units[ingredient!.unit]})</button>.</p>}
      {step.ingredientId && <div className="recipe-fields">{ingredient?.trackingMode !== "availability" && <label className="form-field">Cantidad ({ingredient ? units[ingredient.unit] : "unidad del ingrediente"})<input required inputMode="decimal" value={step.quantity} onChange={event => change(step.stepKey, { quantity: event.target.value })} /></label>}<label className="form-field">Equivalencia para leer (opcional)<input maxLength={120} placeholder="2 cucharadas" value={step.equivalent} onChange={event => change(step.stepKey, { equivalent: event.target.value })} /></label></div>}
      <button type="button" className="core-text-button" onClick={() => { change(step.stepKey, { ingredientId: "", ingredientRevision: null, quantity: "", equivalent: "" }); setIngredientPanels(current => current.filter(key => key !== step.stepKey)); }}>× Quitar ingrediente</button></div>}
      <label className="core-check"><input type="checkbox" checked={step.previous} onChange={event => change(step.stepKey, { previous: event.target.checked, priorGroup: true })} />Hacer este paso antes</label>{step.previous && <div className="recipe-fields">{!step.priorGroup && <label className="form-field">Recordatorio anterior<input required maxLength={150} value={step.priorTitle} onChange={event => change(step.stepKey, { priorTitle: event.target.value })} /></label>}<label className="form-field">Horas antes de la comida<input required type="number" min={0.25} max={8760} step={0.25} value={step.hoursBefore} onChange={event => change(step.stepKey, { hoursBefore: event.target.value })} /></label>{step.priorGroup && <small className="core-muted">Incluye este paso y los anteriores desde el último tramo previo. No completa la comida ni descuenta ingredientes.</small>}</div>}
      <button type="button" className="core-text-button" onClick={() => setOpenStep(null)}>Cerrar edición del paso</button>
    </fieldset>}</section>; })}
    {addingStep ? <section className="recipe-step-composer" aria-label="Agregar paso"><div className="recipe-step-composer-row"><input ref={stepRef} autoFocus={!startInServings} aria-label="Instrucción del nuevo paso" maxLength={2000} disabled={disabled} placeholder="Escribe un paso…" value={pendingStep.text} onChange={event => setPendingStep(current => ({ ...current, text: event.target.value }))} onKeyDown={event => { if (event.key === "Enter" && !event.nativeEvent.isComposing) { event.preventDefault(); if (pendingStep.text.trim()) openIngredientSearch(); } }} /><button type="button" className="core-text-button" disabled={disabled} onClick={openIngredientSearch}>＋ Ingrediente</button><button type="button" className="pantry-add-button" disabled={disabled || !pendingStep.text.trim() || steps.length >= 60} onClick={() => addPendingStep()}>Agregar paso</button></div>
    {pendingIngredient && <div className="recipe-step-composer-row">
      {ingredientSearchOpen ? <StepIngredientSearch catalog={catalog} disabled={disabled} choose={ingredient => { if (ingredient) choose(pendingStep.stepKey, ingredient); else addPendingStep(true); }} create={name => { setIngredientInitialName(name); setIngredientStep(pendingStep.stepKey); }} /> : <>
      <div className="recipe-selected-ingredient"><strong>{catalog.find(entry => entry.id === pendingStep.ingredientId)?.name ?? "Ingrediente"}</strong><button type="button" className="core-text-button" disabled={disabled} onClick={openIngredientSearch}>Cambiar</button></div>
      {catalog.find(item=>item.id===pendingStep.ingredientId)?.trackingMode !== "availability" && <label className="form-field">Cantidad · {units[catalog.find(entry => entry.id === pendingStep.ingredientId)?.unit ?? "piece"]}<input ref={quantityRef} inputMode="decimal" disabled={disabled || !pendingStep.ingredientId} value={pendingStep.quantity} onChange={event => setPendingStep(current => ({ ...current, quantity: event.target.value }))} onKeyDown={event => { if (event.key === "Enter" && !event.nativeEvent.isComposing) { event.preventDefault(); if (checkQuantity(pendingStep.quantity)) focusField(equivalentRef); } }} /></label>}
      <label className="form-field">{catalog.find(item => item.id === pendingStep.ingredientId)?.trackingMode === "availability" ? "Cómo usarlo (opcional)" : "Equivalencia (opcional)"}<input ref={equivalentRef} maxLength={120} disabled={disabled || !pendingStep.ingredientId} placeholder="Al gusto, un chorrito, 2 cucharadas…" value={pendingStep.equivalent} onChange={event => setPendingStep(current => ({ ...current, equivalent: event.target.value }))} onKeyDown={event => { if (event.key === "Enter" && !event.nativeEvent.isComposing) { event.preventDefault(); addPendingStep(); } }} /></label></>}
      <button type="button" className="core-text-button" disabled={disabled} onClick={() => { setPendingIngredient(false); setIngredientSearchOpen(false); setPendingStep(current => ({ ...current, ingredientId: "", ingredientRevision: null, quantity: "", equivalent: "" })); focusField(stepRef); }}>× Quitar ingrediente</button>
    </div>}
    <label className="core-check"><input type="checkbox" disabled={disabled} checked={pendingStep.optional} onChange={event => setPendingStep(current => ({ ...current, optional: event.target.checked }))} />Paso opcional (incluye su ingrediente)</label><label className="core-check"><input type="checkbox" disabled={disabled} checked={pendingStep.previous} onChange={event => setPendingStep(current => ({ ...current, previous: event.target.checked, priorGroup: true }))} />Hacer este paso antes</label>{pendingStep.previous && <><label className="form-field">Horas antes de la comida<input type="number" min={0.25} max={8760} step={0.25} disabled={disabled} value={pendingStep.hoursBefore} onChange={event => setPendingStep(current => ({ ...current, hoursBefore: event.target.value }))} /></label><small className="core-muted">Este paso cierra un tramo previo con los pasos anteriores aún no agrupados.</small></>}</section> : <button type="button" className="core-text-button" aria-label="Agregar paso" disabled={disabled || steps.length >= 60} onClick={() => setAddingStep(true)}>＋</button>}
    {ingredients.data.nextCatalogId && <button type="button" className="core-text-button" disabled={disabled || ingredients.reading} onClick={() => void ingredients.load("catalog", ingredients.data.nextCatalogId!)}>Cargar más ingredientes</button>}
    <IngredientTotals steps={summary} />{error && <p className="pantry-error" role="alert">{error}</p>}{feed.error && <p className="pantry-error" role="alert">{feed.error}</p>}{ingredients.error && <p className="pantry-error" role="alert">{ingredients.error}</p>}
    <p className="core-muted">Los cambios de los pasos se guardan al pulsar Guardar receta.</p><div className="recipe-actions"><button className="pantry-add-button" disabled={disabled}>{feed.busy ? "Guardando…" : "Guardar receta"}</button><button type="button" className="core-text-button" disabled={feed.busy || ingredients.busy} onClick={close}>Cancelar</button>{feed.retry && <button type="button" className="core-text-button" disabled={feed.busy} onClick={feed.reattempt}>Reintentar guardado</button>}</div>
    <p className="core-muted">Las preparaciones previas se ofrecerán al planificar. Aquí no se crean actividades ni se descuenta Alacena.</p>
  </form>;
  return <>{inline ? form : <CoreDialog title={item ? "Editar receta" : "Nueva receta"} close={close}>{form}</CoreDialog>}{ingredientStep && <CoreFeedback.Provider value={{ error: ingredients.error, retry: ingredients.retry, busy: ingredients.busy, reattempt: ingredients.reattempt }}><IngredientEditor initialName={ingredientInitialName} catalog={catalog} disabled={disabled} mutate={ingredients.mutate} close={() => { if (!ingredients.busy) setIngredientStep(null); }} choose={ingredient => { choose(ingredientStep, ingredient); setIngredientStep(null); }} created={ingredientId => { setCreated({ stepKey: ingredientStep, id: ingredientId }); setIngredientStep(null); }} /></CoreFeedback.Provider>}</>;
}
