"use client";
import { coreFetch, localMode } from "../../core/local-data";
import Link from "../../core/local-link";
import { AppNavigation } from "../../core/app-navigation";
import { useMobileLayout } from "../../core/use-mobile-layout";
import { useEffect, useMemo, useRef, useState } from "react";
import type { PlannerSnapshot, MealView, SlotView } from "../../../../reconstruction/core/src/planner";
import { CoreDialog, CoreFeedback } from "../../core/schedule-editor";
import { usePlannerFeed } from "../../core/use-planner-feed";
import { dateParts, labelDate, plusDays, monday } from "../../core/dates";
import { ActivityPopover } from "../../core/activity-popover";
import { TimePicker } from "../../components/time-picker";
import { MealCompletionButton } from "../../core/meal-completion-button";
import { TaskCard } from "../../core/task-card";
import type { Mutate } from "../../core/use-core-feed";
import { MealWeekActions } from "./meal-week-actions";
import { MealEditor, AvailabilityNotice, PlannerFeedback } from "../../core/meal-editor";
type Feed=ReturnType<typeof usePlannerFeed>;
function clock(minute:number){return `${String(Math.floor(minute/60)).padStart(2,"0")}:${String(minute%60).padStart(2,"0")}`;}
const slotTimeFormat = new Intl.DateTimeFormat("es-MX",{hour:"numeric",minute:"2-digit",hour12:true,timeZone:"UTC"});
export function CorePlannerView({initial,initialMealId}:{initial:PlannerSnapshot;initialMealId?:string}){
  const [start,setStart]=useState(initial.start),[days,setDays]=useState(initial.days),[editor,setEditor]=useState<{date:string;slotId:string;meal?:MealView}|null>(null),[slotEditor,setSlotEditor]=useState<{slot?:SlotView}|null>(null),[remove,setRemove]=useState<SlotView|null>(null),[preferences,setPreferences]=useState(false),[reviewId,setReviewId]=useState<string|null>(null);
  const tableRef=useRef<HTMLDivElement>(null),[editorAnchor,setEditorAnchor]=useState<HTMLElement|null>(null);
  const mobile=useMobileLayout();
  const [selectedDay,setSelectedDay]=useState(()=>initial.meals.find(meal=>meal.id===initialMealId)?.date??dateParts(new Date(),initial.timeZone).date);
  function chooseDay(date:string){if(!/^\d{4}-\d{2}-\d{2}$/.test(date))return;setSelectedDay(date);if(date<start||date>=plusDays(start,days))setStart(monday(date));}
  useEffect(()=>{if(mobile&&(selectedDay<start||selectedDay>=plusDays(start,days)))setSelectedDay(start);},[mobile,start,days,selectedDay]);
  const feed=usePlannerFeed(initial,start,days);const today=dateParts(new Date(),initial.timeZone).date,ready=feed.data.start===start&&feed.data.days===days,disabled=feed.locked||!ready||!feed.data.initialized;
  const mealByCell = useMemo(() => new Map(feed.data.meals.map(meal => [`${meal.slotId}:${meal.date}`, meal])), [feed.data.meals]);
  async function openMeal(mealId:string,anchor?:HTMLElement){if(anchor)setEditorAnchor(anchor);const snapshot=await feed.load();if(!snapshot)return;const meal=snapshot.meals.find(item=>item.id===mealId);if(!meal)return;if(meal.completedAt){setEditor(null);setReviewId(meal.id);}else{setReviewId(null);setEditor({date:meal.date,slotId:meal.slotId,meal});}}
  useEffect(()=>{if(initialMealId){const meal=initial.meals.find(item=>item.id===initialMealId);if(meal){if(meal.completedAt){setEditor(null);setReviewId(meal.id);}else{setReviewId(null);setEditor({date:meal.date,slotId:meal.slotId,meal});}}}},[initialMealId,initial.meals]);
  function renderCell(slot:SlotView,date:string){const meal=mealByCell.get(`${slot.id}:${date}`);return <>{meal?<div className="planner-core-meal-card"><MealCompletionButton item={meal.activity} disabled={disabled} mutate={(command,success)=>feed.mutate(command,success)}/><button className="planner-core-meal" disabled={disabled} onClick={event=>void openMeal(meal.id,event.currentTarget)}><small>{dateParts(meal.schedule.startsAt!,meal.schedule.timeZone).time}</small>{meal.recipes.map(item=><span key={item.id}><strong>{item.name}</strong><small>{item.eatenServings} para comer · {meal.cookingEnabled&&Number(item.cookedServings)>0?`${item.cookedServings} para cocinar`:"Sin cocinar"}</small></span>)}{meal.completedAt?<small>✓ Completada</small>:<AvailabilityNotice value={feed.data.availability[meal.id]} timeZone={feed.data.timeZone} compact/>}<small>{meal.completedAt?"Ver comida completada":"Editar comida"}</small></button></div>:<button className="planner-core-add" disabled={disabled} aria-label={`Planificar ${slot.name} el ${date}`} onClick={event=>{setEditorAnchor(event.currentTarget);setReviewId(null);setEditor({date,slotId:slot.id});void feed.load();}}>＋</button>}</>;}
  return <CoreFeedback.Provider value={{error:feed.error,retry:feed.retry,busy:feed.busy,reattempt:feed.reattempt}}><main className="app-shell"><AppNavigation /><section className="workspace"><header className="topbar"><div className="breadcrumb">Cocina / <strong>Planificar</strong></div><Link prefetch={false} className="core-text-button" href="/agenda">Ver Agenda</Link></header><div className="page-content"><div className="page-heading-row"><div><p className="eyebrow">COCINA</p><h1>Planificar comidas</h1><p className="week-range">{mobile?labelDate(selectedDay,{weekday:"long",day:"numeric",month:"long"}):`${labelDate(start)} – ${labelDate(plusDays(start,days-1))}`}</p></div><div className="recipe-actions"><button className="core-text-button" disabled={disabled} onClick={()=>setPreferences(true)}>Tiempos habituales</button></div></div>
    <div className="planner-core-toolbar planner-desktop-toolbar"><button className="core-text-button" disabled={feed.locked} onClick={()=>setStart(plusDays(start,-7))}>← Semana anterior</button><button className="core-text-button" disabled={feed.locked} onClick={()=>setStart(monday(today))}>Esta semana</button><button className="core-text-button" disabled={feed.locked} onClick={()=>setStart(plusDays(start,7))}>Semana siguiente →</button><label className="form-field">Mostrar<select value={days} disabled={feed.locked} onChange={event=>setDays(Number(event.target.value))}><option value={7}>Una semana</option><option value={14}>Dos semanas</option></select></label><button className="core-text-button" disabled={disabled} onClick={()=>setSlotEditor({})}>＋ Tipo de comida</button></div>
    {mobile&&<div className="planner-day-toolbar"><button type="button" className="core-text-button" aria-label="Día anterior" disabled={feed.locked} onClick={()=>chooseDay(plusDays(selectedDay,-1))}>‹</button><label className="form-field">Fecha<input type="date" value={selectedDay} disabled={feed.locked} onChange={event=>chooseDay(event.target.value)}/></label><button type="button" className="core-text-button" aria-label="Día siguiente" disabled={feed.locked} onClick={()=>chooseDay(plusDays(selectedDay,1))}>›</button>{selectedDay!==today&&<button type="button" className="core-text-button" disabled={feed.locked} onClick={()=>chooseDay(today)}>Hoy</button>}<button type="button" className="core-text-button" disabled={disabled} onClick={()=>setSlotEditor({})}>＋ Tipo de comida</button></div>}
    {ready && feed.data.initialized && <div className="meal-weeks-toolbar">{Array.from({length:days/7},(_,index)=><MealWeekActions key={plusDays(start,index*7)} start={plusDays(start,index*7)} feed={feed} disabled={disabled}/>)}</div>}
    <p className="core-muted">Planificar no descuenta ingredientes. Completar registra lo cocinado y comido; deshacer devuelve exactamente lo registrado.</p>{feed.error&&<p className="pantry-error" role="alert">{feed.error}{feed.retry&&<button className="core-text-button" disabled={feed.busy} onClick={feed.reattempt}>Reintentar cambio</button>}</p>}{!feed.data.initialized&&<p>Preparando Cocina…</p>}{(!ready||feed.reading)&&<p role="status">Actualizando planificación…</p>}
    {ready&&<div ref={tableRef}>{mobile?<div className="planner-day-list">{feed.data.slots.map(slot=><section key={slot.id} className="planner-day-slot"><header><div><h2>{slot.name}</h2><small>{slotTimeFormat.format(new Date(`2026-01-01T${clock(slot.startMinute)}:00Z`))}</small></div><div className="recipe-actions"><button type="button" className="core-text-button" disabled={disabled} onClick={()=>setSlotEditor({slot})}>Editar</button><button type="button" className="core-text-button" disabled={disabled} aria-label={`Eliminar fila ${slot.name}`} onClick={()=>setRemove(slot)}>×</button></div></header>{renderCell(slot,selectedDay)}</section>)}</div>:<div className="planner-core-scroll"><table className="planner-core-table"><thead><tr><th scope="col">Comida</th>{Array.from({length:days},(_,index)=>{const date=plusDays(start,index);return <th scope="col" key={date} className={date===today?"planner-core-today":""}>{labelDate(date,{weekday:"short"})}<br/>{labelDate(date,{day:"numeric",month:"short"})}</th>;})}</tr></thead><tbody>{feed.data.slots.map(slot=><tr key={slot.id}><th scope="row"><strong>{slot.name}</strong><small>{slotTimeFormat.format(new Date(`2026-01-01T${clock(slot.startMinute)}:00Z`))}</small><div className="recipe-actions"><button className="core-text-button" disabled={disabled} onClick={()=>setSlotEditor({slot})}>Editar</button><button className="core-text-button" disabled={disabled} aria-label={`Eliminar fila ${slot.name}`} onClick={()=>setRemove(slot)}>×</button></div></th>{Array.from({length:days},(_,index)=>{const date=plusDays(start,index);return <td key={date}>{renderCell(slot,date)}</td>;})}</tr>)}</tbody></table></div>}</div>}
    {!!feed.data.resources.realBatches?.length&&<details className="planner-core-availability"><summary>Porciones cocinadas disponibles</summary>{feed.data.resources.realBatches.map(batch=><p key={batch.id}>{batch.recipeName} · v{batch.version}: {batch.quantity} porciones · {labelDate(dateParts(batch.startsAt,feed.data.timeZone).date)}</p>)}</details>}{ready&&feed.data.initialized&&!feed.data.slots.length&&<p className="today-empty">No tienes filas. Agrega un tipo de comida para empezar.</p>}</div></section>
    {reviewId&&(editorAnchor??tableRef.current)&&feed.data.meals.find(m=>m.id===reviewId)&&<ActivityPopover anchor={(editorAnchor??tableRef.current)!} title="Comida completada" busy={feed.busy} close={()=>setReviewId(null)} dismissOutside={false} className="planner-meal-popover"><MealReview meal={feed.data.meals.find(m=>m.id===reviewId)!} feed={feed} close={()=>{if(!feed.busy)setReviewId(null);}}/></ActivityPopover>}{editor&&(editorAnchor??tableRef.current)&&<ActivityPopover anchor={(editorAnchor??tableRef.current)!} title={editor.meal?"Editar comida":"Planificar comida"} busy={feed.busy} close={()=>setEditor(null)} dismissOutside={false} className="planner-meal-popover"><MealEditor embedded key={editor.meal ? `${editor.meal.id}:${editor.meal.revision}` : "new-meal"} value={editor} feed={feed} reload={()=>{if(editor.meal && window.confirm("¿Descartar los cambios de este formulario y cargar la comida actual?")) void openMeal(editor.meal.id);}} close={()=>{if(!feed.busy)setEditor(null);}}/></ActivityPopover>}{slotEditor&&<SlotEditor slot={slotEditor.slot} feed={feed} close={()=>{if(!feed.busy)setSlotEditor(null);}}/>}{remove&&<RemoveSlot slot={remove} feed={feed} close={()=>{if(!feed.busy)setRemove(null);}}/>}{preferences&&<DefaultsEditor feed={feed} close={()=>{if(!feed.busy)setPreferences(false);}}/>}
  </main></CoreFeedback.Provider>;
}
function MealReview({meal,feed,close}:{meal:MealView;feed:Feed;close:()=>void}){
  const mutate:Mutate=(command,success)=>feed.mutate(command,()=>{if(command.action==="deleteTask")close();success?.();});
  return <><ul className="today-list"><TaskCard item={meal.activity} disabled={feed.locked} mutate={mutate} calendars={[]}/></ul><section className="planner-core-availability"><strong>Origen de las porciones consumidas</strong>{meal.portionSources.map(source=><p key={source.id}>{source.quantity} porciones de {source.name} · v{source.version} · cocinadas el {labelDate(dateParts(source.createdAt,feed.data.timeZone).date)}{source.mealId===meal.id?" en este bloque":" en una comida anterior"}</p>)}{!meal.portionSources.length&&<p>No hay porciones consumidas registradas.</p>}</section><PlannerFeedback feed={feed}/></>;
}
function SlotEditor({slot,feed,close}:{slot?:SlotView;feed:Feed;close:()=>void}){const [id]=useState(()=>slot?.id??crypto.randomUUID()),[name,setName]=useState(slot?.name??""),[time,setTime]=useState(clock(slot?.startMinute??480));return <CoreDialog title={slot?"Editar tipo de comida":"Nuevo tipo de comida"} close={close}><form className="core-edit-form" onSubmit={event=>{event.preventDefault();void feed.mutate({action:"saveMealSlot",id,expectedRevision:slot?.revision??null,name,startMinute:Number(time.slice(0,2))*60+Number(time.slice(3))},close);}}><label className="form-field">Nombre<input required maxLength={80} value={name} disabled={feed.locked} onChange={event=>setName(event.target.value)}/></label><TimePicker label="Hora predeterminada" value={time} disabled={feed.locked} onChange={setTime}/><p className="core-muted">Esta hora se usa en nuevas comidas; las ya planificadas conservan su horario.</p><PlannerFeedback feed={feed}/><button className="pantry-add-button" disabled={feed.locked||!name.trim()}>Guardar fila</button></form></CoreDialog>;}
type Impact={revision:number;dataRevision:string;count:number;examples:{date:string;title:string}[];collisions:string[]};
function RemoveSlot({slot,feed,close}:{slot:SlotView;feed:Feed;close:()=>void}){const [destination,setDestination]=useState(""),[impact,setImpact]=useState<Impact|null>(null),[error,setError]=useState<string|null>(null),[confirmed,setConfirmed]=useState(false),[generation,setGeneration]=useState(0);
  useEffect(()=>{const abort=new AbortController();setImpact(null);setConfirmed(false);setError(null);const params=new URLSearchParams({view:"slotImpact",id:slot.id});if(destination)params.set("destinationId",destination);void coreFetch(`/api/core?${params}`,{cache:"no-store",signal:abort.signal}).then(async response=>{const result=await response.json();if(!response.ok)throw new Error(result.message??"No pudimos revisar la fila.");if(!abort.signal.aborted)setImpact(result);}).catch(cause=>{if(!abort.signal.aborted)setError(cause instanceof Error?cause.message:"No pudimos revisar.");});return()=>abort.abort();},[slot.id,destination,generation]);
  return <CoreDialog title={`Eliminar fila ${slot.name}`} close={close}><div className="core-edit-form"><label className="form-field">Qué hacer con sus comidas<select value={destination} disabled={feed.locked} onChange={event=>setDestination(event.target.value)}><option value="">Borrar sus planes y preparaciones</option>{feed.data.slots.filter(item=>item.id!==slot.id).map(item=><option key={item.id} value={item.id}>Trasladar a {item.name}</option>)}</select></label>{!impact&&!error&&<p>Revisando todas las fechas…</p>}{impact&&<><p>Afecta {impact.count} comidas de todas las fechas, no solo esta semana.</p><ul>{impact.examples.map((item,index)=><li key={index}>{item.date}: {item.title}</li>)}</ul>{impact.count>impact.examples.length&&<p>Y {impact.count-impact.examples.length} más.</p>}{impact.collisions.length>0&&<p className="pantry-error">El destino tiene celdas ocupadas en: {impact.collisions.join(", ")}. Elige otra fila o resuelve esas comidas primero.</p>}<label className="core-check"><input type="checkbox" checked={confirmed} disabled={feed.locked} onChange={event=>setConfirmed(event.target.checked)}/>Confirmo el alcance</label><button className="pantry-add-button" disabled={feed.locked||!confirmed||impact.collisions.length>0} onClick={()=>void feed.mutate({action:"removeMealSlot",id:slot.id,expectedRevision:impact.revision,expectedDataRevision:impact.dataRevision,destinationId:destination||null},close)}>{destination?"Trasladar y eliminar fila":"Borrar planes y eliminar fila"}</button></>}{error&&<p className="pantry-error">{error}</p>}<button className="core-text-button" disabled={feed.locked} onClick={()=>setGeneration(value=>value+1)}>Actualizar alcance</button><PlannerFeedback feed={feed}/></div></CoreDialog>;
}
function DefaultsEditor({feed,close}:{feed:Feed;close:()=>void}){const [eating,setEating]=useState(feed.data.eatingMinutes),[washing,setWashing]=useState(feed.data.washingMinutes),[base]=useState(feed.data.dataRevision);return <CoreDialog title="Tiempos habituales" close={close}><form className="core-edit-form" onSubmit={event=>{event.preventDefault();void feed.mutate({action:"saveMealDefaults",eatingMinutes:eating,washingMinutes:washing,expectedDataRevision:base},close);}}><label className="form-field">Minutos para comer<input type="number" required min={0} max={1440} disabled={feed.locked} value={eating} onChange={event=>setEating(Number(event.target.value))}/></label><label className="form-field">Minutos para lavar<input type="number" required min={0} max={1440} disabled={feed.locked} value={washing} onChange={event=>setWashing(Number(event.target.value))}/></label><p className="core-muted">Se usarán en nuevos bloques; los existentes conservan sus tiempos.</p><PlannerFeedback feed={feed}/><button className="pantry-add-button" disabled={feed.locked}>Guardar preferencias</button></form></CoreDialog>;}
